import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'app.name': 'Ruma',
    'app.tagline': 'water solutions',
    'nav.home': 'Home',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.orders': 'Orders',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.terms': 'Terms',
    
    // Home
    'home.hero_title_1': 'Pure Water,',
    'home.hero_title_2': 'Better Life.',
    'home.hero_subtitle': 'Discover our premium range of water purifiers and solutions designed to keep your family healthy and hydrated.',
    'home.search_placeholder': 'Search for water solutions...',
    'home.filters': 'Filters',
    'home.category': 'Category',
    'home.max_price': 'Max Price',
    'home.reset_filters': 'Reset Filters',
    'home.categories': 'Categories',
    'home.all_categories': 'All Categories',
    'home.featured_products': 'Featured Products',
    'home.no_products': 'No products found',
    'home.no_products_subtitle': 'Try adjusting your search or filters.',
    'home.clear_filters': 'Clear Filters',
    
    // Product Card
    'product.view': 'View Details',
    'product.order_now': 'Order Now',
    'product.add_to_cart': 'Add to Cart',
    'product.out_of_stock': 'Out of Stock',
    'product.in_stock': 'In Stock',
    'product.reviews': 'Customer Reviews',
    'product.min_order': 'Minimum order quantity: {count}',
    'product.write_review': 'Write a Review',
    'product.review_placeholder': 'Share your experience with this product...',
    'product.submit_review': 'Submit Review',
    'product.sign_in_review': 'Please sign in to write a review.',
    'product.no_reviews': 'No reviews yet. Be the first to review this product!',
    'product.ready_to_order': 'Ready to Order?',
    'product.get_delivered': 'Get this product delivered right to your doorstep.',

    // Common
    'common.view_all': 'View All',
    'common.back': 'Back',
    'common.scan_barcode': 'Scan Barcode / QR',
    
    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.empty_subtitle': 'Looks like you haven\'t added any products yet.',
    'cart.start_shopping': 'Start Shopping',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.quantity': 'Quantity',
    'cart.unit_price': 'Unit Price',
    'cart.items': 'items',
    'cart.checkout': 'Proceed to Checkout',
    'cart.processing': 'Processing...',
    'cart.recently_viewed': 'Recently Viewed Products',
    'cart.no_recently_viewed': 'No recently viewed products',
    'cart.wishlist_section': 'My Wishlist',
    'cart.orders_section': 'Order History',
    'cart.view_all': 'View All',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.wishlist': 'My wishlist',
    'profile.orders': 'My orders',
    'profile.account_settings': 'Account Settings',
    'profile.language': 'Language',
    'profile.customer_care': 'Customer Care',
    'customer_care.title': 'Customer Care Support',
    'customer_care.name': 'Name',
    'customer_care.email': 'Email',
    'customer_care.problem_type': 'Problem Type',
    'customer_care.select_problem': 'Select Problem',
    'customer_care.delivery': 'Delivery Issue',
    'customer_care.payment': 'Payment Issue',
    'customer_care.product': 'Product Issue',
    'customer_care.other': 'Other',
    'customer_care.submit': 'Create Ticket',
    'customer_care.success': 'Your support ticket has been created!',
    'customer_care.ticket_id': 'Ticket ID',
    'customer_care.contact_info': 'Our customer support team will contact you within 24 hours.',
    'customer_care.back_home': 'Back to Home',
    'customer_care.fill_all': 'Please fill in all information',
    'customer_care.success_toast': 'Your support ticket has been created!',
    'customer_care.details': 'Problem Details',
    'customer_care.details_placeholder': 'Please describe your problem in detail...',
    'profile.terms': 'Terms and Conditions',
    'profile.about': 'About',
    'profile.logout': 'Logout',
    'profile.app_version': 'App Version',
    'profile.select_language': 'Select Language',
    'profile.english': 'English',
    'profile.bengali': 'Bengali',
    'profile.delete_account': 'Delete Account',
    'profile.delete_confirm_title': 'Delete Account?',
    'profile.delete_confirm_desc': 'This action is irreversible. All your data, including orders and wishlist, will be permanently removed.',
    'profile.delete_cancel': 'Cancel',
    'profile.delete_confirm_btn': 'Yes, Delete My Account',
    'profile.account_deleted_success': 'Account deleted successfully',
    'profile.account_delete_error': 'Failed to delete account. Please try again.',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.product_details': 'Product Details',
    'checkout.your_details': 'Your Details',
    'checkout.payment': 'Payment',
    'checkout.shipping': 'Shipping',
    'checkout.step_details': 'Details',
    'checkout.step_shipping': 'Shipping',
    'checkout.step_payment': 'Payment',
    'checkout.full_name': 'Full Name',
    'checkout.phone_number': 'Phone Number',
    'checkout.building_no': 'Building/House No.',
    'checkout.street': 'Street',
    'checkout.landmark': 'Landmark',
    'checkout.city': 'City',
    'checkout.district': 'District',
    'checkout.state': 'State',
    'checkout.pincode': 'Pincode',
    'checkout.address_type': 'Address Type',
    'checkout.home': 'Home',
    'checkout.work': 'Work/Office',
    'checkout.continue_to_payment': 'Continue to Payment',
    'checkout.order_summary': 'Order Summary',
    'checkout.total_amount': 'Total Amount',
    'checkout.select_payment_method': 'Select Payment Method',
    'checkout.card_payment': 'Credit / Debit Card',
    'checkout.coming_soon': 'Coming Soon',
    'checkout.card_desc': 'Pay securely with your card',
    'checkout.upi_qr': 'UPI / QR',
    'checkout.upi_desc': 'Google Pay, PhonePe, Paytm',
    'checkout.enter_utr': 'Enter UTR / Reference Number',
    'checkout.upload_screenshot': 'Upload Payment Screenshot',
    'checkout.click_to_upload': 'Click to upload',
    'checkout.drag_drop': 'or drag and drop',
    'checkout.file_types': 'PNG, JPG or JPEG',
    'checkout.cod': 'Cash on Delivery',
    'checkout.cod_desc': 'Pay when you receive the order',
    'checkout.verify_place_order': 'Verify Payment & Place Order',
    'checkout.select_upi_app': 'Select a UPI App above to Pay',
    'checkout.pay_place_order': 'Pay ₹{amount} & Place Order',
    'checkout.processing': 'Processing...',
    'checkout.back': 'Back',
    'checkout.continue': 'Continue',
    'checkout.utr_placeholder': 'e.g. 312345678901',
    'checkout.utr_help': 'After successful payment, please enter the 12-digit transaction reference number.',
    'checkout.screenshot_help': 'Upload a screenshot of your successful payment. We will verify the UTR number automatically.',
    'checkout.name_placeholder': 'Enter your full name',
    'checkout.phone_placeholder': 'Enter your phone number',
    'checkout.building_placeholder': 'Building or House Number',
    'checkout.street_placeholder': 'Street name or number',
    'checkout.landmark_placeholder': 'Near a known place (optional)',
    'checkout.loading_order': 'Loading order details...',
    'checkout.order_not_found': 'Order Not Found',
    'checkout.order_not_found_desc': 'We couldn\'t find the order you\'re looking for. It might have been removed or the link is invalid.',
    'checkout.back_home': 'Back to Home',
    'checkout.order_confirmed': 'Order Confirmed!',
    'checkout.thank_you': 'Thank you for your purchase, {name}!',
    'checkout.order_id': 'Order ID',
    'checkout.quantity': 'Quantity',
    'checkout.subtotal': 'Subtotal',
    'checkout.free': 'Free',
    'checkout.total_paid': 'Total Paid',
    'checkout.est_delivery': 'Estimated Delivery',
    'checkout.preparing_shipping': 'We are preparing your order for shipping.',
    'checkout.shipping_details': 'Shipping Details',
    'checkout.recipient': 'Recipient',
    'checkout.address': 'Address',
    'checkout.payment_method': 'Payment Method',
    'checkout.view_orders': 'View My Orders',
    'checkout.continue_shopping': 'Continue Shopping',
    'checkout.need_help': 'Need help with your order?',
    'checkout.contact_support': 'Contact Customer Support',
    
    // Order Confirmation
    'conf.title': 'Order Confirmed!',
    'conf.success_msg': 'Thank you for your purchase. Your order has been placed successfully.',
    'conf.order_id': 'Order ID',
    'conf.view_orders': 'View My Orders',
    'conf.continue_shopping': 'Continue Shopping',
    'conf.shipping_address': 'Shipping Address',
    'conf.payment_details': 'Payment Details',
    'conf.method': 'Method',
    'conf.utr': 'UTR Number',
    'conf.items': 'Items',
    'conf.total': 'Total',
    'conf.status': 'Status',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.no_orders': 'You haven\'t placed any orders yet.',
    'orders.empty': 'No orders yet',
    'orders.empty_subtitle': 'When you place orders, they will appear here.',
    'orders.start_shopping': 'Start Shopping',
    'orders.sign_in': 'Please sign in to view your orders.',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Items',
    'orders.order_id': 'Order ID',
    'orders.status_pending': 'Pending',
    'orders.status_processing': 'Processing',
    'orders.status_shipped': 'Shipped',
    'orders.status_delivered': 'Delivered',
    
    // Wishlist
    'wishlist.title': 'My Wishlist',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.empty_subtitle': 'Save items you like to your wishlist.',
    'wishlist.start_shopping': 'Start Shopping',
    'wishlist.sign_in': 'Please sign in to view your wishlist.',
    'login.title': 'Welcome Back',
    'login.google': 'Log in with Google',
    'login.or_email': 'Or continue with email',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.button': 'Log In',
    'login.logging_in': 'Logging in...',
    'login.no_account': "Don't have an account?",
    'login.signup': 'Sign up',
    'login.signup_required_title': 'Sign Up Required!',
    'login.signup_required_desc': 'We couldn\'t find your account in our system. Please sign up to create your profile and start using the app.',
    'login.signup_now': 'SIGN UP NOW',
    'signup.title': 'Create Account',
    'signup.name': 'Full Name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.button': 'Sign Up',
    'signup.signing_up': 'Signing up...',
    'signup.have_account': 'Already have an account?',
    'signup.login': 'Log In',
  },
  bn: {
    // Common
    'app.name': 'রুমা',
    'app.tagline': 'ওয়াটার সলিউশনস',
    'nav.home': 'হোম',
    'nav.cart': 'কার্ট',
    'nav.wishlist': 'উইশলিস্ট',
    'nav.orders': 'অর্ডার',
    'nav.profile': 'প্রোফাইল',
    'nav.admin': 'অ্যাডমিন',
    'nav.login': 'লগইন',
    'nav.signup': 'সাইন আপ',
    'nav.terms': 'শর্তাবলী',
    
    // Home
    'home.hero_title_1': 'বিশুদ্ধ জল,',
    'home.hero_title_2': 'উন্নত জীবন।',
    'home.hero_subtitle': 'আপনার পরিবারকে সুস্থ এবং হাইড্রেটেড রাখতে ডিজাইন করা আমাদের প্রিমিয়াম ওয়াটার পিউরিফায়ার এবং সলিউশনগুলি আবিষ্কার করুন।',
    'home.search_placeholder': 'ওয়াটার সলিউশন খুঁজুন...',
    'home.filters': 'ফিল্টার',
    'home.category': 'বিভাগ',
    'home.max_price': 'সর্বোচ্চ মূল্য',
    'home.reset_filters': 'ফিল্টার রিসেট করুন',
    'home.categories': 'বিভাগসমূহ',
    'home.all_categories': 'সব বিভাগ',
    'home.featured_products': 'সেরা পণ্যসমূহ',
    'home.no_products': 'কোনো পণ্য পাওয়া যায়নি',
    'home.no_products_subtitle': 'আপনার অনুসন্ধান বা ফিল্টার পরিবর্তন করার চেষ্টা করুন।',
    'home.clear_filters': 'ফিল্টার মুছুন',
    
    // Product Card
    'product.view': 'বিস্তারিত দেখুন',
    'product.order_now': 'এখনই অর্ডার করুন',
    'product.add_to_cart': 'কার্টে যোগ করুন',
    'product.out_of_stock': 'স্টক শেষ',
    'product.in_stock': 'স্টক আছে',
    'product.reviews': 'গ্রাহকের পর্যালোচনা',
    'product.min_order': 'ন্যূনতম অর্ডারের পরিমাণ: {count}টি',
    'product.write_review': 'একটি পর্যালোচনা লিখুন',
    'product.review_placeholder': 'এই পণ্যটির সাথে আপনার অভিজ্ঞতা শেয়ার করুন...',
    'product.submit_review': 'পর্যালোচনা জমা দিন',
    'product.sign_in_review': 'পর্যালোচনা লিখতে অনুগ্রহ করে সাইন ইন করুন।',
    'product.no_reviews': 'এখনও কোনো পর্যালোচনা নেই। এই পণ্যটি পর্যালোচনা করার প্রথম ব্যক্তি হন!',
    'product.ready_to_order': 'অর্ডার করতে প্রস্তুত?',
    'product.get_delivered': 'এই পণ্যটি সরাসরি আপনার দোরগোড়ায় পৌঁছে দিন।',

    // Common
    'common.view_all': 'সব দেখুন',
    'common.back': 'পিছনে',
    'common.scan_barcode': 'বারকোড / কিউআর স্ক্যান করুন',
    
    // Cart
    'cart.title': 'আপনার কার্ট',
    'cart.empty': 'আপনার কার্ট খালি',
    'cart.empty_subtitle': 'মনে হচ্ছে আপনি এখনও কোনো পণ্য যোগ করেননি।',
    'cart.start_shopping': 'কেনাকাটা শুরু করুন',
    'cart.summary': 'অর্ডার সারসংক্ষেপ',
    'cart.subtotal': 'সাবটোটাল',
    'cart.shipping': 'শিপিং',
    'cart.total': 'মোট',
    'cart.quantity': 'পরিমাণ',
    'cart.unit_price': 'একক মূল্য',
    'cart.items': 'টি পণ্য',
    'cart.checkout': 'চেকআউট করুন',
    'cart.processing': 'প্রসেসিং...',
    'cart.recently_viewed': 'সম্প্রতি দেখা পণ্যসমূহ',
    'cart.no_recently_viewed': 'সম্প্রতি কোনো পণ্য দেখা হয়নি',
    'cart.wishlist_section': 'আমার উইশলিস্ট',
    'cart.orders_section': 'অর্ডার ইতিহাস',
    'cart.view_all': 'সব দেখুন',
    
    // Profile
    'profile.title': 'আমার প্রোফাইল',
    'profile.wishlist': 'আমার উইশলিস্ট',
    'profile.orders': 'আমার অর্ডার',
    'profile.account_settings': 'অ্যাকাউন্ট সেটিংস',
    'profile.language': 'ভাষা',
    'profile.customer_care': 'কাস্টমার কেয়ার',
    'customer_care.title': 'কাস্টমার কেয়ার সাপোর্ট',
    'customer_care.name': 'নাম',
    'customer_care.email': 'ইমেইল',
    'customer_care.problem_type': 'সমস্যার ধরন',
    'customer_care.select_problem': 'নির্বাচন করুন',
    'customer_care.delivery': 'ডেলিভারি সমস্যা',
    'customer_care.payment': 'পেমেন্ট সমস্যা',
    'customer_care.product': 'পণ্য সংক্রান্ত সমস্যা',
    'customer_care.other': 'অন্যান্য',
    'customer_care.submit': 'টিকিট তৈরি করুন',
    'customer_care.success': 'আপনার সাপোর্ট টিকিট সফলভাবে তৈরি হয়েছে!',
    'customer_care.ticket_id': 'টিকিট আইডি',
    'customer_care.contact_info': 'আমাদের কাস্টমার সাপোর্ট টিম ২৪ ঘণ্টার মধ্যে আপনার সাথে যোগাযোগ করবে।',
    'customer_care.back_home': 'হোম পেজে ফিরে যান',
    'customer_care.fill_all': 'অনুগ্রহ করে সব তথ্য পূরণ করুন',
    'customer_care.success_toast': 'আপনার সাপোর্ট টিকিট তৈরি হয়েছে!',
    'customer_care.details': 'সমস্যার বিস্তারিত',
    'customer_care.details_placeholder': 'আপনার সমস্যাটি বিস্তারিতভাবে বর্ণনা করুন...',
    'profile.terms': 'শর্তাবলী',
    'profile.about': 'সম্পর্কে',
    'profile.logout': 'লগআউট',
    'profile.app_version': 'অ্যাপ ভার্সন',
    'profile.select_language': 'ভাষা নির্বাচন করুন',
    'profile.english': 'ইংরেজি',
    'profile.bengali': 'বাংলা',
    'profile.delete_account': 'অ্যাকাউন্ট মুছে ফেলুন',
    'profile.delete_confirm_title': 'অ্যাকাউন্ট মুছে ফেলবেন?',
    'profile.delete_confirm_desc': 'এই কাজটি অপরিবর্তনীয়। অর্ডার এবং উইশলিস্ট সহ আপনার সমস্ত তথ্য স্থায়ীভাবে মুছে ফেলা হবে।',
    'profile.delete_cancel': 'বাতিল',
    'profile.delete_confirm_btn': 'হ্যাঁ, আমার অ্যাকাউন্ট মুছে ফেলুন',
    'profile.account_deleted_success': 'অ্যাকাউন্ট সফলভাবে মুছে ফেলা হয়েছে',
    'profile.account_delete_error': 'অ্যাকাউন্ট মুছতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    
    // Checkout
    'checkout.title': 'চেকআউট',
    'checkout.product_details': 'পণ্যের বিবরণ',
    'checkout.your_details': 'আপনার বিবরণ',
    'checkout.payment': 'পেমেন্ট',
    'checkout.shipping': 'শিপিং',
    'checkout.step_details': 'বিবরণ',
    'checkout.step_shipping': 'শিপিং',
    'checkout.step_payment': 'পেমেন্ট',
    'checkout.full_name': 'পুরো নাম',
    'checkout.phone_number': 'ফোন নম্বর',
    'checkout.building_no': 'বিল্ডিং/বাড়ি নম্বর',
    'checkout.street': 'রাস্তা',
    'checkout.landmark': 'ল্যান্ডমার্ক',
    'checkout.city': 'শহর',
    'checkout.district': 'জেলা',
    'checkout.state': 'রাজ্য',
    'checkout.pincode': 'পিনকোড',
    'checkout.address_type': 'ঠিকানার ধরন',
    'checkout.home': 'বাসা',
    'checkout.work': 'কাজ/অফিস',
    'checkout.continue_to_payment': 'পেমেন্টে এগিয়ে যান',
    'checkout.order_summary': 'অর্ডার সারসংক্ষেপ',
    'checkout.total_amount': 'মোট পরিমাণ',
    'checkout.select_payment_method': 'পেমেন্ট পদ্ধতি নির্বাচন করুন',
    'checkout.card_payment': 'ক্রেডিট / ডেবিট কার্ড',
    'checkout.coming_soon': 'শীঘ্রই আসছে',
    'checkout.card_desc': 'আপনার কার্ড দিয়ে নিরাপদে পেমেন্ট করুন',
    'checkout.upi_qr': 'ইউপিআই / কিউআর',
    'checkout.upi_desc': 'গুগল পে, ফোনপে, পেটিএম',
    'checkout.enter_utr': 'ইউটিআর / রেফারেন্স নম্বর লিখুন',
    'checkout.upload_screenshot': 'পেমেন্ট স্ক্রিনশট আপলোড করুন',
    'checkout.click_to_upload': 'আপলোড করতে ক্লিক করুন',
    'checkout.drag_drop': 'অথবা ড্র্যাগ অ্যান্ড ড্রপ করুন',
    'checkout.file_types': 'পিএনজি, জেপিজি বা জেপিইজি',
    'checkout.cod': 'ক্যাশ অন ডেলিভারি',
    'checkout.cod_desc': 'অর্ডার পাওয়ার সময় পেমেন্ট করুন',
    'checkout.verify_place_order': 'পেমেন্ট যাচাই করুন এবং অর্ডার করুন',
    'checkout.select_upi_app': 'পেমেন্ট করতে উপরে একটি ইউপিআই অ্যাপ নির্বাচন করুন',
    'checkout.pay_place_order': '₹{amount} পেমেন্ট করুন এবং অর্ডার করুন',
    'checkout.processing': 'প্রসেসিং...',
    'checkout.back': 'পিছনে',
    'checkout.continue': 'এগিয়ে যান',
    'checkout.utr_placeholder': 'যেমন: 312345678901',
    'checkout.utr_help': 'সফল পেমেন্টের পর, দয়া করে ১২-সংখ্যার লেনদেন রেফারেন্স নম্বরটি লিখুন।',
    'checkout.screenshot_help': 'আপনার সফল পেমেন্টের একটি স্ক্রিনশট আপলোড করুন। আমরা স্বয়ংক্রিয়ভাবে ইউটিআর নম্বর যাচাই করব।',
    'checkout.name_placeholder': 'আপনার পুরো নাম লিখুন',
    'checkout.phone_placeholder': 'আপনার ফোন নম্বর লিখুন',
    'checkout.building_placeholder': 'বিল্ডিং বা বাড়ি নম্বর',
    'checkout.street_placeholder': 'রাস্তার নাম বা নম্বর',
    'checkout.landmark_placeholder': 'কাছাকাছি কোনো পরিচিত জায়গা (ঐচ্ছিক)',
    'checkout.loading_order': 'অর্ডারের বিবরণ লোড হচ্ছে...',
    'checkout.order_not_found': 'অর্ডার পাওয়া যায়নি',
    'checkout.order_not_found_desc': 'আপনি যে অর্ডারটি খুঁজছেন তা আমরা খুঁজে পাইনি। এটি সরানো হতে পারে বা লিঙ্কটি অবৈধ।',
    'checkout.back_home': 'হোমে ফিরে যান',
    'checkout.order_confirmed': 'অর্ডার নিশ্চিত করা হয়েছে!',
    'checkout.thank_you': 'আপনার ক্রয়ের জন্য ধন্যবাদ, {name}!',
    'checkout.order_id': 'অর্ডার আইডি',
    'checkout.quantity': 'পরিমাণ',
    'checkout.subtotal': 'সাবটোটাল',
    'checkout.free': 'ফ্রি',
    'checkout.total_paid': 'মোট পেমেন্ট',
    'checkout.est_delivery': 'আনুমানিক ডেলিভারি',
    'checkout.preparing_shipping': 'আমরা আপনার অর্ডারটি শিপিংয়ের জন্য প্রস্তুত করছি।',
    'checkout.shipping_details': 'শিপিংয়ের বিবরণ',
    'checkout.recipient': 'প্রাপক',
    'checkout.address': 'ঠিকানা',
    'checkout.payment_method': 'পেমেন্ট পদ্ধতি',
    'checkout.view_orders': 'আমার অর্ডার দেখুন',
    'checkout.continue_shopping': 'কেনাকাটা চালিয়ে যান',
    'checkout.need_help': 'আপনার অর্ডারের জন্য সাহায্য প্রয়োজন?',
    'checkout.contact_support': 'কাস্টমার সাপোর্টে যোগাযোগ করুন',

    // Order Confirmation
    'conf.title': 'অর্ডার নিশ্চিত করা হয়েছে!',
    'conf.success_msg': 'আপনার কেনাকাটার জন্য ধন্যবাদ। আপনার অর্ডারটি সফলভাবে সম্পন্ন হয়েছে।',
    'conf.order_id': 'অর্ডার আইডি',
    'conf.view_orders': 'আমার অর্ডার দেখুন',
    'conf.continue_shopping': 'কেনাকাটা চালিয়ে যান',
    'conf.shipping_address': 'শিপিং ঠিকানা',
    'conf.payment_details': 'পেমেন্ট বিবরণ',
    'conf.method': 'পদ্ধতি',
    'conf.utr': 'ইউটিআর নম্বর',
    'conf.items': 'পণ্যসমূহ',
    'conf.total': 'মোট',
    'conf.status': 'স্ট্যাটাস',
    
    // Orders
    'orders.title': 'আমার অর্ডার',
    'orders.no_orders': 'আপনি এখনও কোনো অর্ডার করেননি।',
    'orders.empty': 'এখনও কোনো অর্ডার নেই',
    'orders.empty_subtitle': 'আপনি যখন অর্ডার করবেন, সেগুলি এখানে দেখা যাবে।',
    'orders.start_shopping': 'কেনাকাটা শুরু করুন',
    'orders.sign_in': 'আপনার অর্ডার দেখতে অনুগ্রহ করে সাইন ইন করুন।',
    'orders.status': 'স্ট্যাটাস',
    'orders.date': 'তারিখ',
    'orders.total': 'মোট',
    'orders.items': 'পণ্যসমূহ',
    'orders.order_id': 'অর্ডার আইডি',
    'orders.status_pending': 'পেন্ডিং',
    'orders.status_processing': 'প্রসেসিং',
    'orders.status_shipped': 'শিপড',
    'orders.status_delivered': 'ডেলিভারড',
    
    // Wishlist
    'wishlist.title': 'আমার উইশলিস্ট',
    'wishlist.empty': 'আপনার উইশলিস্ট খালি',
    'wishlist.empty_subtitle': 'আপনার পছন্দের পণ্যগুলি উইশলিস্টে সেভ করুন।',
    'wishlist.start_shopping': 'কেনাকাটা শুরু করুন',
    'wishlist.sign_in': 'আপনার উইশলিস্ট দেখতে অনুগ্রহ করে সাইন ইন করুন।',
    'login.title': 'স্বাগতম',
    'login.google': 'গুগল দিয়ে লগ ইন করুন',
    'login.or_email': 'অথবা ইমেল দিয়ে চালিয়ে যান',
    'login.email': 'ইমেল',
    'login.password': 'পাসওয়ার্ড',
    'login.button': 'লগ ইন করুন',
    'login.logging_in': 'লগ ইন হচ্ছে...',
    'login.no_account': 'অ্যাকাউন্ট নেই?',
    'login.signup': 'সাইন আপ করুন',
    'login.signup_required_title': 'সাইন আপ প্রয়োজন!',
    'login.signup_required_desc': 'আমাদের সিস্টেমে আপনার অ্যাকাউন্ট পাওয়া যায়নি। আপনার প্রোফাইল তৈরি করতে এবং অ্যাপটি ব্যবহার শুরু করতে অনুগ্রহ করে সাইন আপ করুন।',
    'login.signup_now': 'এখনই সাইন আপ করুন',
    'signup.title': 'অ্যাকাউন্ট তৈরি করুন',
    'signup.name': 'পুরো নাম',
    'signup.email': 'ইমেল',
    'signup.password': 'পাসওয়ার্ড',
    'signup.button': 'সাইন আপ করুন',
    'signup.signing_up': 'সাইন আপ হচ্ছে...',
    'signup.have_account': 'ইতিমধ্যেই অ্যাকাউন্ট আছে?',
    'signup.login': 'লগ ইন করুন',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
